### ISSUE TITLE
PronunciationAssessment\BrowserJS: return an error   'dict' object is not callable

### ISSUE THREAD

**Issue by MagTun** [Azure-Samples/Cognitive-Speech-TTS#215]
I have followed the explanation for the [BrowserJS](https://github.com/Azure-Samples/Cognitive-Speech-TTS/tree/master/PronunciationAssessment/BrowserJS):
- I downloaded the code from the main [repo](https://github.com/Azure-Samples/Cognitive-Speech-TTS)
-  I have added my subscription_key and my region in `Cognitive-Speech-TTS-master\PronunciationAssessment\BrowserJS\application.py` 
- I have placed the `microsoft.cognitiveservices.speech.sdk.bundle.js` in the folder `Cognitive-Speech-TTS-master\PronunciationAssessment\BrowserJS\static` 
- I ran a cmd inside the `BrowserJS` folder and install all the requirements.txt 
- Still inside the cmd, I run the command `set FLASK_APP=application.py` , `set FLASK_ENV=development` and `flask run`
- I then opened the IP where I am able to enter a word and record an audio (I can play it back)

But then I get the loading image (with the blue arc turning) and nothing more happens. In the cmd I get this error: 

```
TypeError: 'dict' object is not callable
The view function did not return a valid response. The return type must be a string, tuple, Response instance, or WSGI callable, but it was a dict.

```
I tried on a python 3.6 and then on a python 3.9 installation

Prinscreen
![image](https://user-images.githubusercontent.com/15843700/137365559-daf229b8-e9ad-4d9d-ac81-472a347fb12f.png)

```
C:\Users\Me\Desktop\Cognitive-Speech-TTS-master\PronunciationAssessment\BrowserJS>flask run
 * Serving Flask app "application.py" (lazy loading)
 * Environment: development
 * Debug mode: on
 * Restarting with windowsapi reloader
 * Debugger is active!
 * Debugger PIN: 383-505-320
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [14/Oct/2021 19:05:29] "←[37mGET / HTTP/1.1←[0m" 200 -
127.0.0.1 - - [14/Oct/2021 19:05:30] "←[37mPOST /gettoken HTTP/1.1←[0m" 200 -
127.0.0.1 - - [14/Oct/2021 19:05:44] "←[1m←[35mPOST /ackaud HTTP/1.1←[0m" 500 -
Traceback (most recent call last):
  File "c:\users\me\appdata\local\programs\python\python36\lib\site-packages\flask\app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "c:\users\me\appdata\local\programs\python\python36\lib\site-packages\flask\app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "c:\users\me\appdata\local\programs\python\python36\lib\site-packages\flask\app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\me\appdata\local\programs\python\python36\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\me\appdata\local\programs\python\python36\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\me\appdata\local\programs\python\python36\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "c:\users\me\appdata\local\programs\python\python36\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "c:\users\me\appdata\local\programs\python\python36\lib\site-packages\flask\app.py", line 1982, in make_response
    reraise(TypeError, new_error, sys.exc_info()[2])
  File "c:\users\me\appdata\local\programs\python\python36\lib\site-packages\flask\_compat.py", line 34, in reraise
    raise value.with_traceback(tb)
  File "c:\users\me\appdata\local\programs\python\python36\lib\site-packages\flask\app.py", line 1974, in make_response
    rv = self.response_class.force_type(rv, request.environ)
  File "c:\users\me\appdata\local\programs\python\python36\lib\site-packages\werkzeug\wrappers.py", line 921, in force_type
    response = BaseResponse(*_run_wsgi_app(response, environ))
  File "c:\users\me\appdata\local\programs\python\python36\lib\site-packages\werkzeug\wrappers.py", line 59, in _run_wsgi_app
    return _run_wsgi_app(*args)
  File "c:\users\me\appdata\local\programs\python\python36\lib\site-packages\werkzeug\test.py", line 923, in run_wsgi_app
    app_rv = app(environ, start_response)
TypeError: 'dict' object is not callable
The view function did not return a valid response. The return type must be a string, tuple, Response instance, or WSGI callable, but it was a dict.
```

**Comment by MagTun** [comment]
The problem was that some of my python packages were not updated when running `pip install -r requirements.txt` (I didn't use a virtual environnement as recommended). When I set up a virtual environnement it works. 
After that I tried again to do a pip install with update (-U) without a virtual environment, it updated my packages and it is now working. 
So instead of running  `pip install -r requirements.txt`, I had to run `pip install -r requirements.txt  -U`

To create a virtual environnement
- pip install virtualenv
- go to the BrowserJS and open a cmd then run
- `virtualenv -p python3 myenv`
- `\myenv\Scripts\activate`
- you should now see a `(myenv)` before the working folder of the cmd and now run 
- `pip install -r requirements.txt`
- `set FLASK_APP=application.py`
- `set FLASK_ENV=development`
- `flask run`
