### ISSUE TITLE
Error on Windows 10 

### ISSUE THREAD

**Issue by prwani-microsoft** [Azure-Samples/Cognitive-Speech-TTS#74]
c:\Solutions\Cognitive-Speech-TTS\Samples-Http\NodeJS>npm install
npm WARN NodeJS No repository field.
npm WARN NodeJS No license field.

up to date in 0.479s

c:\Solutions\Cognitive-Speech-TTS\Samples-Http\NodeJS>node TTSSample.js
c:\Solutions\Cognitive-Speech-TTS\Samples-Http\NodeJS\node_modules\bindings\bindings.js:96
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → c:\Solutions\Cognitive-Speech-TTS\Samples-Http\NodeJS\node_modules\speaker\build\binding.node
 → c:\Solutions\Cognitive-Speech-TTS\Samples-Http\NodeJS\node_modules\speaker\build\Debug\binding.node
 → c:\Solutions\Cognitive-Speech-TTS\Samples-Http\NodeJS\node_modules\speaker\build\Release\binding.node
 → c:\Solutions\Cognitive-Speech-TTS\Samples-Http\NodeJS\node_modules\speaker\out\Debug\binding.node
 → c:\Solutions\Cognitive-Speech-TTS\Samples-Http\NodeJS\node_modules\speaker\Debug\binding.node
 → c:\Solutions\Cognitive-Speech-TTS\Samples-Http\NodeJS\node_modules\speaker\out\Release\binding.node
 → c:\Solutions\Cognitive-Speech-TTS\Samples-Http\NodeJS\node_modules\speaker\Release\binding.node
 → c:\Solutions\Cognitive-Speech-TTS\Samples-Http\NodeJS\node_modules\speaker\build\default\binding.node
 → c:\Solutions\Cognitive-Speech-TTS\Samples-Http\NodeJS\node_modules\speaker\compiled\8.11.1\win32\x64\binding.node
    at bindings (c:\Solutions\Cognitive-Speech-TTS\Samples-Http\NodeJS\node_modules\bindings\bindings.js:93:9)
    at Object.<anonymous> (c:\Solutions\Cognitive-Speech-TTS\Samples-Http\NodeJS\node_modules\speaker\index.js:8:34)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (c:\Solutions\Cognitive-Speech-TTS\Samples-Http\NodeJS\TTSService.js:12:15)

**Comment by prwani-microsoft** [comment]
I could solve the problem by running “npm install --global --production windows-build-tools” using administrator privileges as suggested at stackoverflow (https://stackoverflow.com/questions/21658832/npm-install-error-msb3428-could-not-load-the-visual-c-component-vcbuild-ex)
